name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.18.1"
          registry-url: "https://registry.npmjs.org"
          cache: npm
      - name: Release
        run: |
          npm install
          npm run build
          npx semantic-release
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git config --global user.name "site-eng-github-actions"
          git commit -am "chore: release"
          git push origin main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_PAT }}
